version: '3'
services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 8000:80
    depends_on:
      - api
      - client
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    environment:
      PGUSER: postgres
      PGPASSWORD: 123456
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: postgres
    volumes:
      - ./api:/app
    depends_on:
      - postgres
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
    stdin_open: true
